import requests
from backend.config import OLLAMA_URL, MODEL_NAME


def build_prompt(question: str) -> str:
    return f"""
Answer the student question clearly.

Answer only questions related to university student services such as:
- course registration
- examination rules
- library services
- ICT support
- hostel application
- fee payment
- academic calendar
- student conduct

Use simple, clear, and professional language.
If the question is outside university student support, politely say you can only help with university support topics.

Student question:
{question}
"""


def ask_local_llm(question: str) -> str:
    prompt = build_prompt(question)

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=60)
        response.raise_for_status()

        data = response.json()
        return data.get("response", "No response generated by the model.")

    except requests.exceptions.ConnectionError:
        raise ConnectionError("Local LLM is not running. Please start Ollama and run the model.")

    except requests.exceptions.Timeout:
        raise TimeoutError("The model took too long to respond. Please try again.")

    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"LLM request failed: {str(e)}")